php/asp-gallery-project/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using CRUD.Models;
using System.IO;

namespace CRUD.Controllers
{
    public class HomeController : Controller
    {
        kingdomEntities db = new kingdomEntities();

        public ActionResult Index()
        {
            ViewBag.Projects = db.Projects;
            ViewBag.Languages = db.Languages;
            return View();
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            return View(db.Projects.Where(x => x.ProjectId == id).FirstOrDefault());
        }

        // GET: Computers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Computers/Create
        [HttpPost]
        public ActionResult Create(Project project)
        {
            try
            {
                string fileName = Path.GetFileNameWithoutExtension(project.ImagePath.FileName);
                string extension = Path.GetExtension(project.ImagePath.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                project.ProjectImage = "~/Images/" + fileName;
                fileName = Path.Combine(Server.MapPath("~/Images/"), fileName);
                project.ImagePath.SaveAs(fileName);
                db.Projects.Add(project);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Computers/Edit/5
        [HttpGet]

        public ActionResult Edit(int id)
        {
            return View(db.Projects.Where(x => x.ProjectId == id).FirstOrDefault());
        }

        // POST: Apartament/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Project project)
        {
            try
            {
                string fileName = Path.GetFileNameWithoutExtension(project.ImagePath.FileName);
                string extension = Path.GetExtension(project.ImagePath.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                project.ProjectImage = "~/Images/" + fileName;
                fileName = Path.Combine(Server.MapPath("~/Images/"), fileName);
                project.ImagePath.SaveAs(fileName);
                db.Entry(project).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Apartament/Delete/5
        [HttpGet]

        public ActionResult Delete(int id)
        {
            return View(db.Projects.Where(x => x.ProjectId == id).FirstOrDefault());
        }

        // POST: Apartament/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Project project)
        {
            try
            {
                project = db.Projects.Where(x => x.ProjectId == id).FirstOrDefault();
                db.Projects.Remove(project);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

php/asp-gallery-project/Controllers/LanguageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using CRUD.Models;
using System.IO;

namespace CRUD.Controllers
{
    public class LanguageController : Controller
    {
        kingdomEntities db = new kingdomEntities();
        public ActionResult Details(int id)
        {
            return View(db.Languages.Where(x => x.LanguageId == id).FirstOrDefault());
        }

        // GET: Computers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Computers/Create
        [HttpPost]
        public ActionResult Create(Language language)
        {
            try
            {
                string fileName = Path.GetFileNameWithoutExtension(language.ImagePath.FileName);
                string extension = Path.GetExtension(language.ImagePath.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                language.LanguageImage = "~/Images/" + fileName;
                fileName = Path.Combine(Server.MapPath("~/Images/"), fileName);
                language.ImagePath.SaveAs(fileName);
                db.Languages.Add(language);
                db.SaveChanges();
                return RedirectToAction("../Home/Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Computers/Edit/5
        [HttpGet]

        public ActionResult Edit(int id)
        {
            return View(db.Languages.Where(x => x.LanguageId == id).FirstOrDefault());
        }

        // POST: Apartament/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Language language)
        {
            try
            {
                string fileName = Path.GetFileNameWithoutExtension(language.ImagePath.FileName);
                string extension = Path.GetExtension(language.ImagePath.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                language.LanguageImage = "~/Images/" + fileName;
                fileName = Path.Combine(Server.MapPath("~/Images/"), fileName);
                language.ImagePath.SaveAs(fileName);
                db.Languages.Add(language);
                db.Entry(language).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("../Home/Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Apartament/Delete/5
        [HttpGet]

        public ActionResult Delete(int id)
        {
            return View(db.Languages.Where(x => x.LanguageId == id).FirstOrDefault());
        }

        // POST: Apartament/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Language language)
        {
            try
            {
                language = db.Languages.Where(x => x.LanguageId == id).FirstOrDefault();
                db.Languages.Remove(language);
                db.SaveChanges();

                return RedirectToAction("../Home/Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

php/asp-gallery-project/Views/Home/Create.cshtml
@model CRUD.Models.Project

@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>STEFDOM - Create Page</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="https://icon-library.com/images/f10ca02c9c.svg.svg" rel="icon">
    <link href="https://icon-library.com/images/f10ca02c9c.svg.svg" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Jost:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/Content/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/vendor/icofont/icofont.min.css" rel="stylesheet">
    <link href="~/Content/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/Content/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/Content/vendor/venobox/venobox.css" rel="stylesheet">
    <link href="~/Content/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/Content/vendor/aos/aos.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/Content/css/style.css" rel="stylesheet">

</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top ">
        <div class="container d-flex align-items-center">

            <h1 class="logo mr-auto"><a href="Index">STEFDOM</a></h1>
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href="index.html" class="logo mr-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

            <nav class="nav-menu d-none d-lg-block">
                <ul>
                    <li class="active" aria-hidden="true" hidden><a href="Index">Home</a></li>
                </ul>
            </nav><!-- .nav-menu -->

            <a href="Index" class="get-started-btn scrollto">Home</a>

        </div>
    </header><!-- End Header -->
    <!-- ======= Hero Section ======= -->
    <section id="hero" class="d-flex align-items-center" style="min-height:100vh;">

        <div class="container" >
            <div class="row">
                <div class="col-lg-6 d-flex flex-column justify-content-center pt-4 pt-lg-0 order-2 order-lg-1" data-aos="fade-up" data-aos-delay="200">
                    @using (Html.BeginForm("Create", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            <h4 style="color:white;">Add a new Project</h4>
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group" >
                                @Html.LabelFor(model => model.ProjectName, htmlAttributes: new { @class = "control-label col-md-2 text-light" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.ProjectName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ProjectName, "", new { @class = "alert-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.ProjectLink, htmlAttributes: new { @class = "control-label col-md-2 text-light" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.ProjectLink, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ProjectLink, "", new { @class = "alert-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.ProjectImage, htmlAttributes: new { @class = "control-label col-md-2 text-light" })
                                <div class="col-md-10">
                                    <input type="file" name="ImagePath" class="text-light"/>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Add Project" class="btn btn-primary" />
                                </div>
                            </div>
                        </div>
                    }

                    <div>
                        @Html.ActionLink("Go Back", "Index")
                    </div>

                    @section Scripts {
                        @Scripts.Render("~/bundles/jqueryval")
                    }
                </div>
                <div class="col-lg-6 order-1 order-lg-2 hero-img" data-aos="zoom-in" data-aos-delay="200">
                    <img src="~/Content/img/hero-img.png" class="img-fluid animated" alt="">
                </div>
            </div>
        </div>

    </section><!-- End Hero -->
        <footer id="footer">
            <div class="container footer-bottom clearfix">
                <div class="copyright">
                    &copy; Copyright <strong><span>STEFDOM</span></strong>. All Rights Reserved
                </div>
                <div class="credits">
                    Made by <a href="https://stefanportfolio.netlify.app/">Stefan Golban</a>
                </div>
            </div>
        </footer><!-- End Footer -->

        <a href="#" class="back-to-top"><i class="ri-arrow-up-line"></i></a>
        <div id="preloader"></div>

        <!-- Vendor JS Files -->
        <script src="~/Content/vendor/jquery/jquery.min.js"></script>
        <script src="~/Content/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="~/Content/vendor/jquery.easing/jquery.easing.min.js"></script>
        <script src="~/Content/vendor/php-email-form/validate.js"></script>
        <script src="~/Content/vendor/waypoints/jquery.waypoints.min.js"></script>
        <script src="~/Content/vendor/isotope-layout/isotope.pkgd.min.js"></script>
        <script src="~/Content/vendor/venobox/venobox.min.js"></script>
        <script src="~/Content/vendor/owl.carousel/owl.carousel.min.js"></script>
        <script src="~/Content/vendor/aos/aos.js"></script>

        <!-- Template Main JS File -->
        <script src="~/Content/js/main.js"></script>

</body>

</html>

php/asp-gallery-project/Views/Home/Delete.cshtml
@model CRUD.Models.Project

@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>STEFDOM - Details Page</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="https://icon-library.com/images/f10ca02c9c.svg.svg" rel="icon">
    <link href="https://icon-library.com/images/f10ca02c9c.svg.svg" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Jost:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/Content/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/vendor/icofont/icofont.min.css" rel="stylesheet">
    <link href="~/Content/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/Content/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/Content/vendor/venobox/venobox.css" rel="stylesheet">
    <link href="~/Content/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/Content/vendor/aos/aos.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/Content/css/style.css" rel="stylesheet">

</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top ">
        <div class="container d-flex align-items-center">

            <h1 class="logo mr-auto"><a href="Index">STEFDOM</a></h1>
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href="index.html" class="logo mr-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

            <nav class="nav-menu d-none d-lg-block">
                <ul>
                    <li class="active" aria-hidden="true" hidden><a href="Index">Home</a></li>
                </ul>
            </nav><!-- .nav-menu -->

            <a href="Index" class="get-started-btn scrollto">Home</a>

        </div>
    </header><!-- End Header -->
    <!-- ======= Hero Section ======= -->
    <section id="hero" class="d-flex align-items-center" style="min-height:100vh;">

        <div class="container">
            <div class="row">
                <div class="col-lg-6 d-flex flex-column justify-content-center pt-4 pt-lg-0 order-2 order-lg-1" data-aos="fade-up" data-aos-delay="200">

                    <h3 class="text-warning">Are you sure you want to delete this?</h3>
                    <div class="text-light">
                        <h1>@Html.DisplayNameFor(model => model.ProjectName)</h1>
                        <hr />
                        <dl class="dl-horizontal">
                            <dt>
                                @Html.DisplayNameFor(model => model.ProjectName)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.ProjectName)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.ProjectLink)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.ProjectLink)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.ProjectImage)
                            </dt>

                            <dd>
                               <img src="@Url.Content(Model.ProjectImage)" width="100px" class="rounded" />
                            </dd>

                        </dl>

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                <input type="submit" value="Delete" class="btn btn-danger" /> |
                                @Html.ActionLink("Go Back", "Index")
                            </div>
                        }
                    </div>
                </div>
                <div class="col-lg-6 order-1 order-lg-2 hero-img" data-aos="zoom-in" data-aos-delay="200">
                    <img src="~/Content/img/hero-img.png" class="img-fluid animated" alt="">
                </div>
            </div>
        </div>

    </section><!-- End Hero -->
    <footer id="footer">
        <div class="container footer-bottom clearfix">
            <div class="copyright">
                &copy; Copyright <strong><span>STEFDOM</span></strong>. All Rights Reserved
            </div>
            <div class="credits">
                Made by <a href="https://stefanportfolio.netlify.app/">Stefan Golban</a>
            </div>
        </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top"><i class="ri-arrow-up-line"></i></a>
    <div id="preloader"></div>

    <!-- Vendor JS Files -->
    <script src="~/Content/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/Content/vendor/jquery.easing/jquery.easing.min.js"></script>
    <script src="~/Content/vendor/php-email-form/validate.js"></script>
    <script src="~/Content/vendor/waypoints/jquery.waypoints.min.js"></script>
    <script src="~/Content/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/Content/vendor/venobox/venobox.min.js"></script>
    <script src="~/Content/vendor/owl.carousel/owl.carousel.min.js"></script>
    <script src="~/Content/vendor/aos/aos.js"></script>

    <!-- Template Main JS File -->
    <script src="~/Content/js/main.js"></script>

</body>

</html>

php/asp-gallery-project/Views/Home/Index.cshtml
@model IEnumerable<CRUD.Models.Project>
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>STEFDOM - Homepage</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="https://icon-library.com/images/f10ca02c9c.svg.svg" rel="icon">
    <link href="https://icon-library.com/images/f10ca02c9c.svg.svg" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Jost:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/Content/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/vendor/icofont/icofont.min.css" rel="stylesheet">
    <link href="~/Content/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/Content/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/Content/vendor/venobox/venobox.css" rel="stylesheet">
    <link href="~/Content/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/Content/vendor/aos/aos.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/Content/css/style.css" rel="stylesheet">

</head>

<body>
    <style>
        .member {
            margin-top: 30px;
        }
    </style>
    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top ">
        <div class="container d-flex align-items-center">

            <h1 class="logo mr-auto"><a href="Index">Stefdom</a></h1>
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href="index.html" class="logo mr-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

            <nav class="nav-menu d-none d-lg-block">
                <ul>
                    <li class="active"><a href="Index">Home</a></li>
                    <li><a href="#about">About</a></li>
                    <li><a href="#portfolio">Portfolio</a></li>
                    <li><a href="#skills">Skills</a></li>
                </ul>
            </nav><!-- .nav-menu -->

        </div>
    </header><!-- End Header -->
    <!-- ======= Hero Section ======= -->
    <section id="hero" class="d-flex align-items-center">

        <div class="container">
            <div class="row">
                <div class="col-lg-6 d-flex flex-column justify-content-center pt-4 pt-lg-0 order-2 order-lg-1" data-aos="fade-up" data-aos-delay="200">
                    <h1>Better Websites For Your Business</h1>
                    <h2>I will create the best version of your dream website!</h2>
                    <div class="d-lg-flex">
                        <a href="#portfolio" class="btn-get-started scrollto">See Works</a>
                    </div>
                </div>
                <div class="col-lg-6 order-1 order-lg-2 hero-img" data-aos="zoom-in" data-aos-delay="200">
                    <img src="~/Content/img/hero-img.png" class="img-fluid animated" alt="">
                </div>
            </div>
        </div>

    </section><!-- End Hero -->

    <main id="main">
        <!-- ======= About Us Section ======= -->
        <section id="about" class="about">
            <div class="container" data-aos="fade-up">

                <div class="section-title">
                    <h2>About Me</h2>
                </div>

                <div class="row content">
                    <div class="col-lg-6">
                        <p style="text-align:center;">
                            Hi, I am Stefan and I'm specializing more in creating optimized and well-built websites in React (Front-end and FullStack).
                            I speak English, Romanian, Russian and few Italian .
                        </p>

                    </div>
                    <div class="col-lg-6 pt-4 pt-lg-0" >
                        <p style="text-align:center;">
                            Able to deliver the best version of your website front end built in React or in pure HTML/CSS/JS.
                            Able to make your website functional, user-friendly and "alive".
                            Able to create mobile-responsive websites at a professional level.
                        </p>
                    </div>
                    <ul style="width:100%; display:flex; justify-content:center; flex-direction:column; align-items:center; margin-top:50px; flex-wrap:wrap;">
                        <li><i class="ri-check-double-line"></i> Front-end Development</li>
                        <li><i class="ri-check-double-line"></i> Back-end Development</li>
                        <li><i class="ri-check-double-line"></i> Responsive Design</li>
                    </ul>
                </div>

            </div>
        </section><!-- End About Us Section -->
        <!-- ======= Portfolio Section ======= -->
        <section id="portfolio" class="portfolio">
            <div class="container" data-aos="fade-up">

                <div class="section-title">
                    <h2>Portfolio</h2>
                    <p>These are some of my works.</p>
                </div>

                <ul id="portfolio-flters" class="d-flex justify-content-center" data-aos="fade-up" data-aos-delay="100">
                    <li>@Html.ActionLink("Add a New project", "Create")</li>
                    <li data-filter="*" class="filter-active">All</li>
                </ul>

                <div class="row portfolio-container" data-aos="fade-up" data-aos-delay="200">
                    @foreach (var item in ViewBag.Projects)
                    {
                        <div class="col-lg-4 col-md-6 portfolio-item filter-app" style="margin: 20px 0;">
                            <div class="portfolio-img"><img src="@Url.Content(item.ProjectImage)" class="img-fluid" alt=""></div>
                            <div class="portfolio-info">
                                <h4>@item.ProjectName</h4>
                                <a href="@Url.Content(item.ProjectImage)" data-gall="portfolioGallery" class="venobox " title="Display Image"><i class="bx bx-plus" style="font-size:20px;"></i></a>
                                <a href="@item.ProjectLink" target="_blank" title="Project Link"><i class="bx bx-link" style="font-size: 20px;"></i></a>
                                <a href="@Url.Action("Edit", "Home", new { id = item.ProjectId })" title="Edit Project"><i class="bx bx-edit text-warning" style="font-size: 20px;"></i></a>
                                <a href="@Url.Action("Details", "Home", new { id = item.ProjectId })" title="Project Details"><i class="bx bx-detail text-info" style="font-size: 20px;"></i></a>
                                <a href="@Url.Action("Delete", "Home", new { id = item.ProjectId })" title="Delete Project"><i class="bx bx-trash-alt text-danger" style="font-size: 20px;"></i></a>
                            </div>
                        </div>
                    }
                    </div>

            </div>
        </section><!-- End Portfolio Section -->
        <!-- ======= Team Section ======= -->
        <section id="skills" class="team section-bg">
            <div class="container" data-aos="fade-up">

                <div class="section-title">
                    <h2>My Skills</h2>
                    <p>Down below I listed my skills / programming languages I know.</p>
                    <p>@Html.ActionLink("Add a New language", "../Language/Create")</p>
                </div>

                <div class="row">
                    @foreach (var lang in ViewBag.Languages)
                    {
                        <div class="col-lg-6">
                            <div class="member d-flex align-items-start" data-aos="zoom-in" data-aos-delay="100">
                                <div class="pic"><img src="@Url.Content(lang.LanguageImage)" class="img-fluid" alt=""></div>
                                <div class="member-info">
                                    <h4>@lang.LanguageName</h4>
                                    <p>@lang.LanguageDescription</p>
                                    <div class="social">
                                        <a href="@lang.LanguageLink"><i class="bx bx-link"></i></a>
                                        <a href="@Url.Action("Edit", "Language", new { id = lang.LanguageId })" title="Edit Language"><i class="bx bx-edit text-warning" ></i></a>
                                        <a href="@Url.Action("Details", "Language", new { id = lang.LanguageId })" title="Language Details"><i class="bx bx-detail text-info" ></i></a>
                                        <a href="@Url.Action("Delete", "Language", new { id = lang.LanguageId })" title="Delete Language"><i class="bx bx-trash-alt text-danger" ></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }


                    </div>

            </div>
        </section><!-- End Team Section -->
        <footer id="footer">
            <div class="container footer-bottom clearfix">
                <div class="copyright">
                    &copy; Copyright <strong><span>STEFDOM</span></strong>. All Rights Reserved
                </div>
                <div class="credits">
                    Made by <a href="https://stefanportfolio.netlify.app/">Stefan Golban</a>
                </div>
            </div>
        </footer><!-- End Footer -->

        <a href="#" class="back-to-top"><i class="ri-arrow-up-line"></i></a>
        <div id="preloader"></div>

        <!-- Vendor JS Files -->
        <script src="~/Content/vendor/jquery/jquery.min.js"></script>
        <script src="~/Content/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="~/Content/vendor/jquery.easing/jquery.easing.min.js"></script>
        <script src="~/Content/vendor/php-email-form/validate.js"></script>
        <script src="~/Content/vendor/waypoints/jquery.waypoints.min.js"></script>
        <script src="~/Content/vendor/isotope-layout/isotope.pkgd.min.js"></script>
        <script src="~/Content/vendor/venobox/venobox.min.js"></script>
        <script src="~/Content/vendor/owl.carousel/owl.carousel.min.js"></script>
        <script src="~/Content/vendor/aos/aos.js"></script>

        <!-- Template Main JS File -->
        <script src="~/Content/js/main.js"></script>

</body>

</html>